module MovieTicketBooking
{
        typedef sequence<string> movieNameList;
        typedef sequence<string> movieIdsList;

        interface MovieTicketBookingInterface
        {
                string addMovieSlots (in string movieID, in string movieName, in long bookingCapacity);
                string removeMovieSlots (in string movieID, in string movieName);
                string listMovieShowsAvailability (in string movieName);

                //customer & admin
                string bookMovieTickets (in string customerID, in string movieID, in string movieName, in long numberOfTickets);
                string getBookingSchedule (in string customerID);
                string cancelMovieTickets (in string customerID,in string movieID,in string movieName,in long numberOfTickets);
                boolean validateUser(in string username,in string password);
                oneway void setPortAndHost(in string hostname, in string port);
//                movieNameList getAllMovieNames();
//                movieIdsList getAllMovieIds(in string movieName);
                string getAllMovieNames();
                string getAllMovieIds(in string movieName);
                string exchangeTickets(in string customerID, in string old_movieName, in string old_movieID, in string new_movieID, in string new_movieName, in long numberOfTickets);
        };
};