package MovieTicketBooking;


/**
* MovieTicketBooking/MovieTicketBookingInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./MovieTicketBooking.idl
* Monday, 3 April, 2023 3:39:14 PM EDT
*/

public interface MovieTicketBookingInterface extends MovieTicketBooking.MovieTicketBookingInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface MovieTicketBookingInterface
