package FrontEnd.MovieTicketBooking;

/**
 * MovieTicketBooking/movieIdsListHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ./idl
 * Sunday, April 9, 2023 5:21:16 o'clock PM EDT
 */

public final class movieIdsListHolder
  implements org.omg.CORBA.portable.Streamable {

  public String value[] = null;

  public movieIdsListHolder() {}

  public movieIdsListHolder(String[] initialValue) {
    value = initialValue;
  }

  public void _read(org.omg.CORBA.portable.InputStream i) {
    value = movieIdsListHelper.read(i);
  }

  public void _write(org.omg.CORBA.portable.OutputStream o) {
    movieIdsListHelper.write(o, value);
  }

  public org.omg.CORBA.TypeCode _type() {
    return movieIdsListHelper.type();
  }
}
