package MovieTicketBooking;


/**
* MovieTicketBooking/movieIdsListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./MovieTicketBooking.idl
* Saturday, 8 April, 2023 8:28:22 AM EDT
*/

public final class movieIdsListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public movieIdsListHolder ()
  {
  }

  public movieIdsListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MovieTicketBooking.movieIdsListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MovieTicketBooking.movieIdsListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MovieTicketBooking.movieIdsListHelper.type ();
  }

}
