package MovieTicketBooking;


/**
* MovieTicketBooking/movieNameListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./MovieTicketBooking.idl
* Monday, 3 April, 2023 3:39:14 PM EDT
*/

public final class movieNameListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public movieNameListHolder ()
  {
  }

  public movieNameListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MovieTicketBooking.movieNameListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MovieTicketBooking.movieNameListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MovieTicketBooking.movieNameListHelper.type ();
  }

}
