package MovieTicketBooking;


/**
* MovieTicketBooking/MovieTicketBookingInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./MovieTicketBooking.idl
* Monday, 3 April, 2023 3:39:14 PM EDT
*/

public abstract class MovieTicketBookingInterfacePOA extends org.omg.PortableServer.Servant
 implements MovieTicketBooking.MovieTicketBookingInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addMovieSlots", new java.lang.Integer (0));
    _methods.put ("removeMovieSlots", new java.lang.Integer (1));
    _methods.put ("listMovieShowsAvailability", new java.lang.Integer (2));
    _methods.put ("bookMovieTickets", new java.lang.Integer (3));
    _methods.put ("getBookingSchedule", new java.lang.Integer (4));
    _methods.put ("cancelMovieTickets", new java.lang.Integer (5));
    _methods.put ("validateUser", new java.lang.Integer (6));
    _methods.put ("setPortAndHost", new java.lang.Integer (7));
    _methods.put ("getAllMovieNames", new java.lang.Integer (8));
    _methods.put ("getAllMovieIds", new java.lang.Integer (9));
    _methods.put ("exchangeTickets", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MovieTicketBooking/MovieTicketBookingInterface/addMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int bookingCapacity = in.read_long ();
         String $result = null;
         $result = this.addMovieSlots (movieID, movieName, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // MovieTicketBooking/MovieTicketBookingInterface/removeMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String $result = null;
         $result = this.removeMovieSlots (movieID, movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // MovieTicketBooking/MovieTicketBookingInterface/listMovieShowsAvailability
       {
         String movieName = in.read_string ();
         String $result = null;
         $result = this.listMovieShowsAvailability (movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //customer & admin
       case 3:  // MovieTicketBooking/MovieTicketBookingInterface/bookMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.bookMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // MovieTicketBooking/MovieTicketBookingInterface/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // MovieTicketBooking/MovieTicketBookingInterface/cancelMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // MovieTicketBooking/MovieTicketBookingInterface/validateUser
       {
         String username = in.read_string ();
         String password = in.read_string ();
         boolean $result = false;
         $result = this.validateUser (username, password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // MovieTicketBooking/MovieTicketBookingInterface/setPortAndHost
       {
         String hostname = in.read_string ();
         String port = in.read_string ();
         this.setPortAndHost (hostname, port);
         out = $rh.createReply();
         break;
       }


  //                movieIdsList getAllMovieIds(in string movieName);
       case 8:  // MovieTicketBooking/MovieTicketBookingInterface/getAllMovieNames
       {
         String $result = null;
         $result = this.getAllMovieNames ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // MovieTicketBooking/MovieTicketBookingInterface/getAllMovieIds
       {
         String movieName = in.read_string ();
         String $result = null;
         $result = this.getAllMovieIds (movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // MovieTicketBooking/MovieTicketBookingInterface/exchangeTickets
       {
         String customerID = in.read_string ();
         String old_movieName = in.read_string ();
         String old_movieID = in.read_string ();
         String new_movieID = in.read_string ();
         String new_movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.exchangeTickets (customerID, old_movieName, old_movieID, new_movieID, new_movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MovieTicketBooking/MovieTicketBookingInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MovieTicketBookingInterface _this() 
  {
    return MovieTicketBookingInterfaceHelper.narrow(
    super._this_object());
  }

  public MovieTicketBookingInterface _this(org.omg.CORBA.ORB orb) 
  {
    return MovieTicketBookingInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class MovieTicketBookingInterfacePOA
