package FrontEnd.MovieTicketBooking;


/**
* MovieTicketBooking/MovieTicketBookingInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./MovieTicketBooking.idl
* Sunday, April 9, 2023 5:21:16 o'clock PM EDT
*/

public interface MovieTicketBookingInterface extends MovieTicketBookingInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MovieTicketBookingInterface
