package FrontEnd.MovieTicketBooking;

/**
 * MovieTicketBooking/MovieTicketBookingInterfaceHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ./idl
 * Sunday, April 9, 2023 5:21:16 o'clock PM EDT
 */

public final class MovieTicketBookingInterfaceHolder
  implements org.omg.CORBA.portable.Streamable {

  public MovieTicketBookingInterface value = null;

  public MovieTicketBookingInterfaceHolder() {}

  public MovieTicketBookingInterfaceHolder(
    MovieTicketBookingInterface initialValue
  ) {
    value = initialValue;
  }

  public void _read(org.omg.CORBA.portable.InputStream i) {
    value = MovieTicketBookingInterfaceHelper.read(i);
  }

  public void _write(org.omg.CORBA.portable.OutputStream o) {
    MovieTicketBookingInterfaceHelper.write(o, value);
  }

  public org.omg.CORBA.TypeCode _type() {
    return MovieTicketBookingInterfaceHelper.type();
  }
}
