package FrontEnd.MovieTicketBooking;

/**
 * MovieTicketBooking/movieNameListHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ./idl
 * Sunday, April 9, 2023 5:21:16 o'clock PM EDT
 */

public final class movieNameListHolder
  implements org.omg.CORBA.portable.Streamable {

  public String value[] = null;

  public movieNameListHolder() {}

  public movieNameListHolder(String[] initialValue) {
    value = initialValue;
  }

  public void _read(org.omg.CORBA.portable.InputStream i) {
    value = movieNameListHelper.read(i);
  }

  public void _write(org.omg.CORBA.portable.OutputStream o) {
    movieNameListHelper.write(o, value);
  }

  public org.omg.CORBA.TypeCode _type() {
    return movieNameListHelper.type();
  }
}
