package MovieTicketBooking;


/**
* MovieTicketBooking/MovieTicketBookingInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./MovieTicketBooking.idl
* Saturday, 8 April, 2023 8:28:22 AM EDT
*/

public interface MovieTicketBookingInterface extends MovieTicketBooking.MovieTicketBookingInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface MovieTicketBookingInterface
