package MovieTicketBooking;

/**
* MovieTicketBooking/MovieTicketBookingInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./MovieTicketBooking.idl
* Monday, 3 April, 2023 3:39:14 PM EDT
*/

public final class MovieTicketBookingInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public MovieTicketBooking.MovieTicketBookingInterface value = null;

  public MovieTicketBookingInterfaceHolder ()
  {
  }

  public MovieTicketBookingInterfaceHolder (MovieTicketBooking.MovieTicketBookingInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MovieTicketBooking.MovieTicketBookingInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MovieTicketBooking.MovieTicketBookingInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MovieTicketBooking.MovieTicketBookingInterfaceHelper.type ();
  }

}
